"""tablas de registro

Revision ID: b853fd98ebea
Revises: 03ebef908a79
Create Date: 2026-08-24 19:14:54.516629

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b853fd98ebea"
down_revision: str | Sequence[str] | None = "03ebef908a79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actividades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("hora_aprox", sa.Time(), nullable=True),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("duracion_min", sa.Integer(), nullable=True),
        sa.Column("intensidad", sa.String(), nullable=True),
        sa.Column("pasos", sa.Integer(), nullable=True),
        sa.Column("distancia_km", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("kcal_est", sa.Integer(), nullable=True),
        sa.Column("origen", sa.String(), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("raw_input", sa.Text(), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "intensidad IS NULL OR intensidad IN ('baja', 'media', 'alta')",
            name="ck_actividades_intensidad",
        ),
        sa.CheckConstraint("origen IN ('texto', 'imagen', 'audio')", name="ck_actividades_origen"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_actividades_user_fecha", "actividades", ["user_id", "fecha"], unique=False)
    op.create_table(
        "comidas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("momento", sa.String(), nullable=False),
        sa.Column("hora_aprox", sa.Time(), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("origen", sa.String(), nullable=False),
        sa.Column("kcal_est", sa.Integer(), nullable=True),
        sa.Column("proteinas_g", sa.Integer(), nullable=True),
        sa.Column("carbs_g", sa.Integer(), nullable=True),
        sa.Column("grasas_g", sa.Integer(), nullable=True),
        sa.Column("raw_input", sa.Text(), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "momento IN ('desayuno', 'almuerzo', 'merienda', 'cena', 'snack')",
            name="ck_comidas_momento",
        ),
        sa.CheckConstraint("origen IN ('texto', 'imagen', 'audio')", name="ck_comidas_origen"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_comidas_user_fecha", "comidas", ["user_id", "fecha"], unique=False)
    op.create_table(
        "metricas_dia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("pasos_total", sa.Integer(), nullable=True),
        sa.Column("fuente", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "fecha", name="uq_metricas_dia_user_fecha"),
    )
    op.create_table(
        "perfiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sexo", sa.String(), nullable=True),
        sa.Column("fecha_nac", sa.Date(), nullable=True),
        sa.Column("altura_cm", sa.Integer(), nullable=True),
        sa.Column("peso_actual_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("objetivo", sa.Text(), nullable=True),
        sa.Column("restricciones", sa.Text(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "pesos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("peso_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pesos_user_fecha", "pesos", ["user_id", "fecha"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pesos_user_fecha", table_name="pesos")
    op.drop_table("pesos")
    op.drop_table("perfiles")
    op.drop_table("metricas_dia")
    op.drop_index("ix_comidas_user_fecha", table_name="comidas")
    op.drop_table("comidas")
    op.drop_index("ix_actividades_user_fecha", table_name="actividades")
    op.drop_table("actividades")
    # ### end Alembic commands ###
