"""examenes y conversacion

Revision ID: e9fc2f49adb3
Revises: b853fd98ebea
Create Date: 2026-08-24 19:15:41.217429

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9fc2f49adb3"
down_revision: str | Sequence[str] | None = "b853fd98ebea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversacion_mensajes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rol", sa.String(), nullable=False),
        sa.Column("contenido", sa.Text(), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("rol IN ('user', 'assistant')", name="ck_conversacion_rol"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversacion_user_creado",
        "conversacion_mensajes",
        ["user_id", "creado_en"],
        unique=False,
    )
    op.create_table(
        "examenes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fecha_estudio", sa.Date(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("archivo_path", sa.Text(), nullable=True),
        sa.Column("resumen", sa.Text(), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_examenes_user_fecha", "examenes", ["user_id", "fecha_estudio"], unique=False
    )
    op.create_table(
        "examen_valores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("examen_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("valor", sa.Text(), nullable=False),
        sa.Column("unidad", sa.Text(), nullable=True),
        sa.Column("ref_min", sa.Text(), nullable=True),
        sa.Column("ref_max", sa.Text(), nullable=True),
        sa.Column("fuera_de_rango", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["examen_id"],
            ["examenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_examen_valores_examen_id"), "examen_valores", ["examen_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_examen_valores_examen_id"), table_name="examen_valores")
    op.drop_table("examen_valores")
    op.drop_index("ix_examenes_user_fecha", table_name="examenes")
    op.drop_table("examenes")
    op.drop_index("ix_conversacion_user_creado", table_name="conversacion_mensajes")
    op.drop_table("conversacion_mensajes")
    # ### end Alembic commands ###
